# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE sevendb;'

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email: false