# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

services:
  - mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS sevendb;'
  - mysql -e 'CREATE DATABASE sevendb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;'

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email: false