spring:
  application:
    name: "SEVEN"
  mandatory-file-encoding: utf-8

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/heroku_b610c580a82293d?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&reconnect=true&useSSL=false
    platform: mysql
    schema: classpath:/db/schema-mysql.sql
    data: classpath:/db/data-mysql.sql
    # set to false after 1st run
    initialize: false
    username: b4c8cdd4df6da0
    password: 1feb6f37
    tomcat:
      test-while-idle: true
      validationQuery: SELECT 1
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 10
      min-idle: 2
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 20000
      max-idle: 5
      initial-size: 5
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      remove-abandoned: true
      test-on-connect: true
      remove-abandoned-timeout: 600

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      hbm2ddl:
        auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  # ===============================
  # = Thymeleaf configurations
  # ===============================
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/

  # ===============================
  # = HTTP/HTTPS
  # ===============================
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

  # ===============================
  # = Email configurations
  # ===============================
  mail:
    host: smtp.gmail.com #localhost
    port: 587 #25
    username: gpg.home@gmail.com
    password: zywrmeegxqntdekv
    properties.mail.smtp:
                     auth: true
                     starttls.enable: true
                     starttls.required: true
    default-encoding: UTF-8
    test-connection: false
    protocol: smtp

# ===============================
# = Tomcat
# ===============================
server:
  port: ${PORT:8080}
  tomcat:
    uri-encoding: UTF-8

# ===============================
# = LOG
# ===============================
logging:
  config: classpath:logback.xml
  level:
    #show sql statement
    org.hibernate.SQL: debug
    #show sql values
    org.hibernate.type.descriptor.sql.BasicBinder: trace