spring:
  application:
    name: "SEVEN"
  mandatory-file-encoding: utf-8

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/sevendb?useSSL=false

    platform: mysql
    schema: classpath:/db/schema-mysql.sql
    data: classpath:/db/data-mysql.sql
    # set to false after 1st run
    initialize: true
    username: root
    password: root
    tomcat:
      test-while-idle: true
      validationQuery: SELECT 1
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 10
      min-idle: 2
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 20000
      max-idle: 5
      initial-size: 5
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      remove-abandoned: true
      test-on-connect: true

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      hbm2ddl:
        auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  # ===============================
  # = Thymeleaf configurations
  # ===============================
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/

  # ===============================
  # = HTTP/HTTPS
  # ===============================
  http:
    encoding:
      charset: UTF-8
      enabled: true

  # ===============================
  # = Email configurations
  # ===============================
  mail:
    host: smtp.gmail.com #localhost
    port: 587 #25
    username: admin
    password: admin
    properties.mail.smtp:
                     auth: true
                     starttls.enable: true
    default-encoding: UTF-8
    #test-connection: true

# ===============================
# = Tomcat
# ===============================
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

# ===============================
# = LOG
# ===============================
logging:
  config: classpath:logback.xml
  #level:
    #show sql statement
    #org.hibernate.SQL: debug
    #show sql values
    #org.hibernate.type.descriptor.sql.BasicBinder: trace